/**
 * smallmodelsapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EnergyQuantity } from './energyQuantity';

/**
* The change in use of one or more types of energy.  This is a model object that gets exposed via OpenAPI.  This is typically the result of a home upgrade of some kind, such as replacing one or more appliances or adding insulation.  It also includes a usage level tag, as tradeoffs are typically different for different levels of use.
*/
export class EnergyTradeoff {
    'usageLevelTag': string;
    'timePeriod'?: string = 'annual';
    'changes': Array<EnergyQuantity>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "usageLevelTag",
            "baseName": "usage_level_tag",
            "type": "string"
        },
        {
            "name": "timePeriod",
            "baseName": "time_period",
            "type": "string"
        },
        {
            "name": "changes",
            "baseName": "changes",
            "type": "Array<EnergyQuantity>"
        }    ];

    static getAttributeTypeMap() {
        return EnergyTradeoff.attributeTypeMap;
    }
}

