/**
 * smallmodelsapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Enum for valid columns to group the query results by.
*/
export enum GroupBy {
    InSqftBin = <any> 'in_sqft_bin',
    AcsHousingType = <any> 'acs_housing_type',
    InHvacCoolingType = <any> 'in_hvac_cooling_type',
    BaselineApplianceFuel = <any> 'baseline_appliance_fuel',
    UpgradeOption = <any> 'upgrade_option'
}
