/**
 * smallmodelsapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Various efficiency standards for electrical HVAC equipment.
*/
export enum HvacEfficiencyElectricDetailed {
    SeerEnergyStarSept2015ToPresent = <any> 'SEER - ENERGY STAR Sept 2015 to present',
    SeerEnergyStar2006ThruAug2015 = <any> 'SEER - ENERGY STAR 2006 thru Aug 2015',
    Seer2015OrNewerSouth = <any> 'SEER - 2015 or newer (South)',
    Seer2015OrNewerNorth = <any> 'SEER - 2015 or newer (North)',
    Seer2006To2014 = <any> 'SEER - 2006 to 2014',
    Seer1992Through2005 = <any> 'SEER - 1992 through 2005',
    SeerPriorTo1992 = <any> 'SEER - Prior to 1992',
    SeerMiniSplitDuctlessAllYears = <any> 'SEER - Mini-split / Ductless (All years)',
    HspfEnergyStarSept2015ToPresent = <any> 'HSPF - ENERGY STAR Sept 2015 to present',
    HspfEnergyStar2006ThruAug2015 = <any> 'HSPF - ENERGY STAR 2006 thru Aug 2015',
    Hspf2015OrNewer = <any> 'HSPF - 2015 or newer',
    Hspf2006To2014 = <any> 'HSPF - 2006 to 2014',
    Hspf1992Through2005 = <any> 'HSPF - 1992 through 2005',
    HspfPriorTo1992 = <any> 'HSPF - Prior to 1992',
    HspfMiniSplitDuctlessAllYears = <any> 'HSPF - Mini-split / Ductless (All years)',
    EerWindowAC = <any> 'EER - Window A/C'
}
