/**
 * smallmodelsapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Standards for measuring efficiency for HVAC systems burning fossil fuels.  One difference from the GGRF spreadsheet is that we break out gas and propane here so that it does not have to be picked with a separate parameter.
*/
export enum HvacEfficiencyFossilFuels {
    EfOil = <any> 'EF - Oil',
    EfGas = <any> 'EF - Gas',
    AfueOilFurnace = <any> 'AFUE - Oil Furnace',
    AfueOilBoiler = <any> 'AFUE - Oil Boiler',
    AfueGasFurnace = <any> 'AFUE - Gas Furnace',
    AfueGasBoiler = <any> 'AFUE - Gas Boiler',
    AfuePropaneFurnace = <any> 'AFUE - Propane Furnace',
    AfuePropaneBoiler = <any> 'AFUE - Propane Boiler'
}
