/**
 * smallmodelsapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Fuel types inputs that the range upgrade API supports.  Note that we do not support electricity as the input because we are modeling upgrading to electric, and so upgrading from electric would produce no change.
*/
export enum RangeFuelType {
    NaturalGas = <any> 'natural_gas',
    Propane = <any> 'propane'
}
