/**
 * smallmodelsapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Enum for valid electrification upgrade options.
*/
export enum UpgradeOption {
    HeatPumpDryer = <any> 'heat_pump_dryer',
    MediumEfficiencyHeatPumpBasicInsulation = <any> 'medium_efficiency_heat_pump_basic_insulation',
    HeatPumpWaterHeater = <any> 'heat_pump_water_heater',
    MediumEfficiencyHeatPump = <any> 'medium_efficiency_heat_pump',
    ElectricResistanceDryer = <any> 'electric_resistance_dryer'
}
