/**
 * smallmodelsapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Enum for valid electrification upgrade options.
*/
export enum UpgradeOption {
    HpDryer = <any> 'hp_dryer',
    MedEffHpHersSizingNoSetbackBasicEnclosure = <any> 'med_eff_hp_hers_sizing_no_setback_basic_enclosure',
    HpWaterHeater = <any> 'hp_water_heater',
    MedEffHpHersSizingNoSetback = <any> 'med_eff_hp_hers_sizing_no_setback',
    ElectricResistanceDryer = <any> 'electric_resistance_dryer'
}
